url: http://underworldfetishnight.com/
baseurl: /

# Site settings
title: underworld Fetish Night
email: info@underworldfetishnight.com
description: "This will be updated shortly"

plugins: 
- jekyll-toc
- jekyll-seo-tag
- jekyll-archives
- jekyll-sitemap
- jekyll-compose
- jekyll-youtube
- jekyll-email-protect
- jekyll-paginate